### ISSUE TITLE
Export SIGO configuration

### ISSUE THREAD

**Issue by giraud10** [CGI-FR/SIGO#29]
```yaml
version: "1"

- k-anonymity: 3
- l-diversity: 1
- aggregation: mean
- rules:
  - name: fieldA
  - name: fieldB
  - name: fieldC
```

```yaml
version: "2"

- k-anonymity: 3
- l-diversity: 1
- rules:
  - name: fieldA
    aggregation: mean
  - name: fieldB
    aggregation: randomNoise
  - name: fieldC
    aggregation: median
```

```yaml
version: "3"

- k-anonymity: 3
- l-diversity: 1
- input-path: "examples/input.json"
- output-path: "examples/output.json"
- rules:
  - name: "fieldA and fieldC"
    aggregation: mean
    match: "fieldA|fieldC"
  - name: fieldB
    aggregation: randomNoise
```
