### ISSUE TITLE
PROPOSOAL: different anonymization methods for qi

### ISSUE THREAD

**Issue by giraud10** [CGI-FR/SIGO#44]
allow in `sigo` configuration to choose the anonymization method for an attribute :

```yaml
version: "2"

kAnonymity: 3
lDiversity: 2
sensitives:
  - s
rules:
  - name: fieldA
    aggregation: mean
  - name: fieldB
    aggregation: randomNoise
  - name: fieldC
    aggregation: median
```
